--- #config apache
- hosts: localhost
  become: yes
  vars:
   var_port: 9000
  tasks:
  - name: install httpd
    yum:
     name: httpd
     state: latest
  - name: template config file switch_port.j2
    template:
     src: switch_port.j2
     dest: /etc/httpd/conf/httpd.conf
    notify:
     - restart httpd
  handlers:
  - name: restart web services
    service:
     name: httpd
     state: restarted
    listen: "restart httpd"
