--- #switch apache port
- hosts: localhost
  become: yes
  tasks:
  - name: install apache
    yum:
     name: httpd
     state: latest
  - name: remplace ligne fichier /etc/httpd/conf/httpd.conf
    shell: sed -i 's/^Listen.*/Listen 9000/' /etc/httpd/conf/httpd.conf
  - name: restart apache
    service:
     name: httpd
     state: restarted    
