--- #Ajout d'un utilisateur ansible et d'un group ansible
- hosts: vagrant
  become:    yes
  vars:
   username:    jenkins
   groupname:    jenkins
  tasks:
  - name:    create a group
    group:
     name:    "{{ groupname }}"
     state:    present
  - name:    create a user
    user:
     name:    "{{ username }}"
     password: '???'
     group:    "{{ groupname }}"
     state:    present
     system:    yes
     create_home:    yes
     home:   "/home/{{ username }}"
