---
# tasks file for test-role-1

- name: install httpd
  yum:
   name: httpd
   state: latest
- name: template config file switch_port.j2
  template:
   src: switch_port.j2
   dest: /etc/httpd/conf/httpd.conf
  notify:
   - restart httpd
