---
# tasks file for JENKINS
- name: creation /usr/lib/jenkins
  file:
    path: /usr/lib/jenkins
    state: directory
    mode: '0755'
- name: creation /data/
  file:
    path: /data/
    state: directory
- name: creation /data/jenkins
  file:
     path: /data/jenkins/
     state: directory
- name: download jenkins.war
  get_url: 
    url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
    dest: /usr/lib/jenkins
- name: creation jenkins.service
  template:
    src: jenkins.service.j2
    dest: /etc/systemd/system/jenkins.service
- name: systemctl restart jenkins
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: jenkins
